### ISSUE TITLE
Are complex filters possible or am I doing something wrong?

### ISSUE THREAD

**Issue by TehWardy** [jcachat/EntityFramework.DynamicFilters#104]
In my code currently I have a method like this ...

```
public override IQueryable<SIHead> GetAll()
{
    return base.GetAll().Where(i =>
        // where user has a factoring relationship to the invoice
        i.FactorCompany.aspnet_Roles
            .Any(r => r.aspnet_Users
                .Any(u => u.UserId == User.UserId) && r.Privileges.Any(p => p.SystemName == factorPrivName))
        ||
        // where user has a buyer relationship to the invoice
        i.BuyerCompanyAux.Company.aspnet_Roles
            .Any(r => r.aspnet_Users
                .Any(u => u.UserId == User.UserId) && r.Privileges.Any(p => p.SystemName == buyerPrivName))
        ||
        // where user has a supplier relationship to the invoice
        i.SupplierCompanyAux.Company.aspnet_Roles
            .Any(r => r.aspnet_Users
                .Any(u => u.UserId == User.UserId) && r.Privileges.Any(p => p.SystemName == supplierPrivName))
        ||
        i.Contacts.Any(c => c.UserId == User.UserId)
    );
}

```
This works a treat, the problem is I need to apply this filter to the EF context as there ways to get to the SIHead table that don't through this service (e.g. OData expands from another endpoint).

My attempt resulted in this in the context ...

```
builder.Filter(
    "VisibleSIHeads",
    (SIHead i, string user) => 
        // where user has a factoring relationship to the invoice
        i.FactorCompany.aspnet_Roles.Any(r => r.aspnet_Users.Any(u => u.UserName == user) && r.Privileges.Any(p => p.SystemName == "Factor View Invoice")) ||
        // where user has a buyer relationship to the invoice
        i.BuyerCompanyAux.Company.aspnet_Roles.Any(r => r.aspnet_Users.Any(u => u.UserName == user) && r.Privileges.Any(p => p.SystemName == "View Invoice")) ||
        // where user has a supplier relationship to the invoice
        i.SupplierCompanyAux.Company.aspnet_Roles.Any(r => r.aspnet_Users.Any(u => u.UserName == user) && r.Privileges.Any(p => p.SystemName == "View Sales Invoice")) ||
        i.Contacts.Any(c => c.User.aspnet_User.UserName == user),
    (CoreDataContext ctx) => ctx.AuthInfo.Name
);
```
... the problem is that it's going "bang" with the following exception ...

```
System.Data.Entity.Core.EntityCommandExecutionException
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
  ....
```

Does filtering support this level of "depth" with nested Any() calls as I saw that Any() is supported (https://github.com/jcachat/EntityFramework.DynamicFilters/commit/248b681495e99391fb42e85549c33d0ddf3618ed) but wondered if there was some limit to it as the unit tests appear to show only 1 level deep Any() calls?

**Comment by TehWardy** [comment]
Ok never mind ... it is supported .. .there was a typo in my code ... nice to know it handles this level of complexity well though :)
