### ISSUE TITLE
Issue with filter that provide filter value with delegate/expression instead of a specific value

### ISSUE THREAD

**Issue by Rinsen** [jcachat/EntityFramework.DynamicFilters#105]
Hi!

When running code with a filter defined in this way
`modelBuilder.Filter("CustomerFilter', (ICustomerSpecific c) => c.CustomerId, () => GetCustomerId());`

And then we get the current customer from our CallContext the is the HttpContext equivalent in WCF in this way
`private static Guid GetCustomerId()
        {
            return CustomerLocator.CustomerId;
        }`

All is good the first 4-5 times we run queries with this but after a very short time the delegate stop all new execution and start to behave in the same way as when we have a specific value.

What could the problem be?

**Comment by jcachat** [comment]
Put a breakpoint inside your GetCustomerId() method to debug it there and to make sure it's being called when you think it should (for each query).  If it's not being called, then I would suspect you are re-using a previously used DbContext object.  Doing so will cause EF to re-use the previously generated query and/or fetch entities from it's internal cache.

**Comment by Rinsen** [comment]
The DbContext are inside a using as I can see but I will verify that we really do that. 

And the way I have found this is by having a break point in that method, any other suggestions on how to troubleshoot?

**Comment by jcachat** [comment]
Were you able to see if you were re-using instances of your DbContext?  I don't have any other suggestions.  I (and many other people) use this same method to get the filter parameter value so I'm not sure what the difference is.

If you can boil it down to post-able code that replicates the issue, I can take a closer look.

**Comment by Rinsen** [comment]
We dispose all DbContext instances as expected so this is not the issue, when debugging the code we found that it will evaluate the delegate the first times but then it suddenly stop evaluate this and starts to handle it as a static mapping.

The current workaround is that we use this instead
`context.SetFilterScopedParameterValue("IsDeleted", true);` 

But it would be very nice to have the typed version instead.

I will try to figure out what is wrong as soon as I find the time and get back to you.

**Comment by rufer7** [comment]
We detected a similar problem.

Given the following filter definition

```C#
modelBuilder.Filter("CurrentTenantFilter", (DataEntity dataEntity, Guid currentTid, Guid sharedTid) =>
                    dataEntity.Tid == currentTid || dataEntity.Tid == sharedTid,
                    () => GetCurrentTenantId(),
                    () => Identity.Tenant.SHARED_TID
            );
```

The method `GetCurrentTenantId()` looks as follows:

```C#
private Guid GetCurrentTenantId()
{
	return securityContext.Identity.Tid;
}
```

With `EntityFramework.DynamicFilters` `v2.6.0` we observed that `GetCurrentTenantId()` method gets executed on the wrong `CustomDbContext` instance. It unexpectedly gets executed on the first ever created `CustomDbContext` instance. This means accessing an instance variable like `securityContext.Identity.Tid` (`tidForTestingPurposes`) will always return the same filter parameter value independent of the corresponding `CustomDbContext` as the `GetCurrentTenantId()` method gets always executed on the same instance (Proven by evaluating `securityContext.GetHashCode()` in different cases)

Furthermore we observed another strange thing.

Passing the parameter values as a constant value in the bool expression will lead to a NullReferenceException in DynamicFilter ExpressionVisitor while converting the Expression to a DB statement.

Given the following filter definition.

```C#
modelBuilder.Filter("CurrentTenantFilter", (DataEntity b, Guid t0) =>
		b.Tid == Identity.Tenant.SHARED_TID || b.Tid == t0,
		() => GetCurrentTenantId()
);
```

During execution the following exception will be thrown.


```
{"Object reference not set to an instance of an object."}

{System.Linq.Expressions.Expression VisitMember(System.Linq.Expressions.MemberExpression)}

   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, DbContext dbContext, DataSpace dataSpace)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.BuildFilterExpressionWithDynamicFilters(IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.Visit(DbScanExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbLimitExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbLimitExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
...
```

**Comment by jcachat** [comment]
@rufer7, If you want to get the parameter value from a method on the current DbContext, you need to specify that like this:
```
modelBuilder.Filter("CurrentTenantFilter", (DataEntity dataEntity, Guid currentTid, Guid sharedTid) =>
                    dataEntity.Tid == currentTid || dataEntity.Tid == sharedTid,
                    (MyDbContext ctx) => ctx.GetCurrentTenantId(),
                    (MyDbContext ctx) => ctx.Identity.Tenant.SHARED_TID
            );
```

Otherwise, you should only be specifying static methods for those delegates.  See here: https://github.com/jcachat/EntityFramework.DynamicFilters#parameter-expressions

Not sure I understand about your null exception.  Maybe it's related to not calling it with the DbContext instance?  If not, please post a full example into a new issue as it's not related to this one.

**Comment by rufer7** [comment]
@jcachat thanks a lot for the explanation. This should solve our problem. From the `README` we could not figure out how to pass the context when having more than one parameter. Probably it makes sense to add an example with two parameters to the `README`!?
