### ISSUE TITLE
TPH : EntitySet not found for <Children> or BaseType <IntermediateType>

### ISSUE THREAD

**Issue by jaenyph** [jcachat/EntityFramework.DynamicFilters#106]
I can't get the library to work on the following case :

I have a base class "`RootObject`" which contains the property "`IsDeleted`" and I have the following classes hierarchy :
```
                                                     RootObject
                                                          |
                                                          O
                                                          |
                                                          S
                                                          |
                      --------------------- ACRS-----------------CA-------HCC-------SC
                      |                       |
                      |          ------------ | ----------
                      |          |      |     |    |     |
                    ANCRS       EC      IC    L    P     RC
               ------|------
               |           |
               H           CC
```

In my context, at the end of the OnModelCreating method, the filter definition is declared like this :

`modelBuilder.Filter("IsDeleted", (RootObject o) => o.IsDeleted, false);`

When I try projecting from a selection of the following leaves classes {`CC`, `EC`, `IC`,  `L`, `P`, `RC`} I get the following exception:

```
EntitySet not found for H or BaseType ANCRS

Stack trace: 
at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.Visit(DbPropertyExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitList[TElement](IList`1 list, Func`2 map)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbNewInstanceExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitList[TElement](IList`1 list, Func`2 map)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbNewInstanceExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
```

This works well for the leaf class `H`, but for the leaf classes involved in the `ANCRS` or `ACRS` hierarchy it fails with the exact same error.

While I can understand there could be a problem with the `CC `class, this is strange that the same exception occurs for the {`EC`, `IC`, `L`, `P`, `RC`} classes because it has nothing to do with the ANCRS base class.

**Comment by jcachat** [comment]
My guess would be that you are hitting the same issue as in #76 in this comment: https://github.com/jcachat/EntityFramework.DynamicFilters/issues/76#issuecomment-284613996

I have not had a chance to make the change suggested in that comment into a new build.  If possible, can you download the source, make that change, and then test to see if it fixes your issue?

I know you have a complicated situation there but if you could minimize it down to a post-able amount of code that replicates the problem, it would help me tremendously.

**Comment by jcachat** [comment]
Thank you!  That PR was a huge help.  I just pushed a new NuGet package with this fix in it.
