### ISSUE TITLE
NullReferenceException when filtering based on Static Variable

### ISSUE THREAD

**Issue by rufer7** [jcachat/EntityFramework.DynamicFilters#109]
**Version:** `2.7.0`
**Database:** MSSQLLocalDB (SQL Server 13.0.2151)

Referring to a static `Guid` value in the filter predicate will lead to a `NullReferenceException` in `ExpressionVisitor` of `DynamicFilters` while converting the Expression to a DB statement.

Given the following filter definition.

```C#
namespace Com.Example.Core.DbContext
{
	public static class Identity
	{
		public static class Tenant
		{
			public const string SYSTEM = "11111111-1111-1111-1111-111111111111";
			public const string SHARED = "44444444-4444-4444-4444-444444444444";

			// ReSharper disable InconsistentNaming
			public static readonly Guid SYSTEM_TID = new Guid(SYSTEM);
			public static readonly Guid SHARED_TID = new Guid(SHARED);
			// ReSharper restore InconsistentNaming
		}
	}

	public class CustomDbContext : BaseDbContext
	{
		private const string SCHEMA_NAME = "arbitrary";

		internal const string CURRENT_TENANT_FILTER_NAME = "CurrentTenantFilter";
		internal const string SYSTEM_TENANT_FILTER_NAME = "SystemTenantFilter";

		private static readonly string _connectionStringName = string.Format(Message.CustomDbContext__ConnectionStringNameTemplate, typeof(CustomDbContext).FullName);

		/// <summary>
		/// Database initialisation
		/// 
		/// For more details see http://www.entityframeworktutorial.net/code-first/database-initialization-in-code-first.aspx
		/// </summary>
		public CustomDbContext()
		{
			// N/A
		}
		
		private Guid GetCurrentTenantId()
		{
			return SecurityContext.GetCurrentTenantId();
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			modelBuilder.HasDefaultSchema(SCHEMA_NAME);

			modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
			modelBuilder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();
			modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();

			base.OnModelCreating(modelBuilder);

			modelBuilder.Filter(CURRENT_TENANT_FILTER_NAME, (DataEntity dataEntity, Guid currentTid) =>
					dataEntity.Tid == currentTid || dataEntity.Tid == Identity.Tenant.SHARED_TID,
					(CustomDbContext ctx) => ctx.GetCurrentTenantId()
			);

			modelBuilder.Filter(SYSTEM_TENANT_FILTER_NAME, (DataEntity dataEntity) =>
					dataEntity.Tid == Identity.Tenant.SYSTEM_TID || dataEntity.Tid == Identity.Tenant.SHARED_TID
			);

			// System tenant filter by default is disabled globally
			modelBuilder.DisableFilterGlobally(SYSTEM_TENANT_FILTER_NAME);
		}

		public DbSet<KeyNameValue> KeyNameValues { get; set; }
	}
}
```

Additional code

```C#
public class BaseDbContext : System.Data.Entity.DbContext
{
	public BaseDbContext(string nameOrConnectionString) 
		: base(nameOrConnectionString)
	{
		// N/A
	}
	
	...
}
```

During execution the following code a `NullReferenceException` will be thrown.

```C#
public virtual TDataEntity Get(long id)
{
	return Db.Set<TDataEntity>().FirstOrDefault(e => e.Id == id);
}
```

```
System.NullReferenceException

{"Object reference not set to an instance of an object."}

   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, DbContext dbContext, DataSpace dataSpace)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.BuildFilterExpressionWithDynamicFilters(IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitorCSpace.Visit(DbScanExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbLimitExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbLimitExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

   ...
```

**Comment by jcachat** [comment]
I haven't dug into this yet so I may or may not be able to handle that.  But...

You should definitely NOT specify parameters directly inside your linq query like that.  That portion of the query will not be parameterized and so parameter values will not be updated each time it's executed.  The best I could possibly do would be to fetch the value when the query is first compiled.  You should specify it as a parameter in the linq query.

**Comment by rufer7** [comment]
@jcachat I don't understand why having a filter as follows should not be correct.

```C#
modelBuilder.Filter(CURRENT_TENANT_FILTER_NAME, (DataEntity dataEntity, Guid currentTid) =>
                    dataEntity.Tid == currentTid || dataEntity.Tid == Identity.Tenant.SHARED_TID,
                    (CustomDbContext ctx) => ctx.GetCurrentTenantId()
            );
```

This filter has 1 parameter, whose value gets update each time it's executed and another value (`Identity.Tenant.SHARED_TID`) which is always the same (similar as a constant). IMHO this should work as well...

**Comment by jcachat** [comment]
The problem is with the "Identity.Tenant.SHARED_TID" parameter being included inside the linq query.  

The way all of this works is the first time EF executes that query, it compiles it.  At that time, I am able to examine the query, extract parameters from it, and replace them with my own placeholders.  Then when the query sql is sent, I intercept it (which happens each time it's executed) and can substitute those placeholders with dynamically updated parameter values.

By including "Identity.Tenant.SHARED_TID" directly in the linq query, there is no dynamic filter parameter for me to fetch & replace.  So it will be left up to EF to handle - which will only happen once during query compile.  This all works a little differently than just a regular linq query because we are injecting this extra filter on your other queries.  We only get 1 shot at that so you can't use parameters that change values inside the filter linq - they have to be specified as parameters.

But...I will take a look at this exception and see if there's a way to handle this syntax.  And then we'll see for sure how it gets handled.  Maybe since it's a static property it will work.  

Re-writing it like this will definitely work though:
```
modelBuilder.Filter(CURRENT_TENANT_FILTER_NAME, (DataEntity dataEntity, Guid currentTid, Guid tid) =>
                    dataEntity.Tid == currentTid || dataEntity.Tid == tid,
                    (CustomDbContext ctx) => ctx.GetCurrentTenantId(),
                    () => Identity.Tenant.SHARED_TID
            );
```

**Comment by rufer7** [comment]
@jcachat first of all great job! Thank you very much for the fast answer and the detailed explanation. Now I understand how it works. It would be great if you could anyway have a look at this exception. I really appreciate your responsiveness! 

The code snippet you pasted does not compile. To make it compiling it has to be extended as follows:

```C#
modelBuilder.Filter(CURRENT_TENANT_FILTER_NAME, (DataEntity dataEntity, Guid currentTid, Guid tid) =>
                    dataEntity.Tid == currentTid || dataEntity.Tid == tid,
                    (CustomDbContext ctx) => ctx.GetCurrentTenantId(),
                    (CustomDbContext ctx) => Identity.Tenant.SHARED_TID
            );
```

**Comment by jcachat** [comment]
Build 2.8 has been pushed out to NuGet with this fix.  Let me know how that works.

Just keep in mind that any values embedded directly in the linq statement (not as parameters) will be treated as constant values.  That value will be fetched the first time the query is compiled by EF.  So if the value changes, it will not be reflected in future queries.
