### ISSUE TITLE
List() parameter - NullReference

### ISSUE THREAD

**Issue by babinecm** [jcachat/EntityFramework.DynamicFilters#45]
Hello,
I've tried to define filter with Contains() operator just like in your example.
This is what I have defined:
```
var values = new List<int> { 1, 2, 3, 4, 5 };
var values2 = new List<int?> { null, 1, 2, 3, 4, 5 };
modelBuilder.Filter(DataFilters.MustHavePlace, (IMustHavePlace p, List<int> placeList) => placeList.Contains(p.PlaceId), () => values);
modelBuilder.Filter(DataFilters.MayHavePlace, (IMayHavePlace p, List<int?> placeList) => placeList.Contains(p.PlaceId), () => values2);
```
If I'll call the query for the specified entity it will always return the following exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
at EntityFramework.DynamicFilters.DynamicFilterExtensions.SetSqlParameters(DbContext context, DbCommand command)
at EntityFramework.DynamicFilters.DynamicFilterCommandInterceptor.SetDynamicFilterParameterValues(DbCommand command, DbContext context)
at EntityFramework.DynamicFilters.DynamicFilterCommandInterceptor.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__d(IDbCommandInterceptor i, DbCommand t, DbCommandInterceptionContext`1 c)
at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult](IEnumerable`1 sequence)
at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
```

**Comment by jcachat** [comment]
I don't see anything wrong with your filter.  Can you provide some more information:
1) Version of EF and of the DynamicFilter library
2) Database & version you are using
3) The 2 models & interfaces you are referencing (just the relevant parts - enough so I can try to reproduce the problem).

**Comment by babinecm** [comment]
Here are additional information:
1) EF v6.1.3, I've also tried v6.1.2 and v6.1.1, but without success. DynamicFilters v1.4.1.
2) DB is MS SQL 2014 on localhost and MS SQL 2012 on production machine.
3)
IMustHavePlace interface
```
public interface IMustHavePlace
{
    int PlaceId { get; set; }
}
```
IMayHavePlace interface
```
public interface IMayHavePlace
{
    int? PlaceId { get; set; }
}
```
Place model
```
public class Place
{
    public virtual int Id { get; set; }
    
    public virtual string Name { get; set; }

    public virtual string Description { get; set; }

    public virtual string Street { get; set; }

    public virtual string City { get; set; }

    public virtual string Zip { get; set; }

    public virtual string CountryCode { get; set; }

    public virtual ICollection<Machine> Machines { get; set; }

    public virtual ICollection<Article> Articles { get; set; }
}
```
Machine model implements IMayHavePlace interface
```
public class Machine : IMayHavePlace
{
    public virtual int Id { get; set; }

    public virtual string MachineNumber { get; set; }

    public virtual string Name { get; set; }

    public virtual string Description { get; set; }

    [ForeignKey("PlaceId")]
    public virtual Place Place { get; set; }

    public virtual int? PlaceId { get; set; }
}
```
Article model implements IMustHavePlace interface
```
public class Article : IMustHavePlace
{
    public virtual int Id { get; set; }
    
    public virtual string Name { get; set; }

    public virtual string Description { get; set; }

    public virtual string Ean { get; set; }

    [ForeignKey("PlaceId")]
    public virtual Place Place { get; set; }

    public virtual int PlaceId { get; set; }
}
```

**Comment by jcachat** [comment]
I used your models and filters to try to reproduce the problem.  I am not getting the same error as you, but there is a problem with this filter:
```
var values2 = new List<int?> { null, 1, 2, 3, 4, 5 };
modelBuilder.Filter(DataFilters.MayHavePlace, (IMayHavePlace p, List<int?> placeList) => placeList.Contains(p.PlaceId), () => values2);
```

The problem is with the handling of a nullable list and how the null check is being done for the null value.  I actually have a unit test for this same type of filter and I have the test condition wrong so I didn't notice that it wasn't working.  This is fixable but it may take a bit of work so it might be a few days.

In the mean time, you can create your filter like this and it will accomplish the same thing:
```
var values2 = new List<int> { 1, 2, 3, 4, 5 };
modelBuilder.Filter(DataFilters.MayHavePlace, (IMayHavePlace p, List<int> placeList) => !p.PlaceId.HasValue || placeList.Contains(p.PlaceId.Value), () => values2);
```

Can you try that and see if it clears up your errors?  If not, I may need a full test project that reproduces the problem.

**Comment by babinecm** [comment]
I tried change the filter as you suggested, but without success, still the same error. Problem is both IMustHavePlace and IMayHavePlace are producing this error.

I'm using ABP Framework (http://aspnetboilerplate.com/) in my project and I'm waiting to confirm that there is no problem with DynamicFilters. See http://forum.aspnetboilerplate.com/viewtopic.php?f=2&t=484.

You can try to generate a new template project from their web site and you can test filters on that project.
Maybe it will be helpful.

**Comment by jcachat** [comment]
Sorry for the late response.  I think I just tracked this down to a context.Database.Log call.  That's only done when using a List/Contains() and I was not checking to make sure there was actually a logger attached!  I just checked in a fix and pushed out an update to NuGet.  Let me know if that fixes it for you.

**Comment by babinecm** [comment]
I can confirm it is fully working. We can close this issue.
Thank you very much.
