### ISSUE TITLE
Disabled filters still executing during request

### ISSUE THREAD

**Issue by themephs** [jcachat/EntityFramework.DynamicFilters#59]
Maybe I've done something wrong, but here's the situation, and there are three observable problems here:

I have a number of dynamically generated filters at application startup to support "access rules" where the application admin can map certain model properties to a role or user so that they can/can't access any db entities with the criteria matching the access rule.  These filters are generated and then immediately have called this.DisableFilterGlobally on it, only being enabled for the span of the request when the user or role attached to a certain filter is relevant.

The problem appears to be that these filters are globally disabled, but are still executing.  In debug I checked the filters myself by using this.IsFilterEnabled(nameOfFilter) and it comes back FALSE!  The only filters where a "Contain" expression is being used should be disabled for these requests however, and as I said, I checked all of the possible filters which could trip this exception and they are reported as enabled == false according to this.IsFilterEnabled.

So why would they be executing?  The exception is posted at the bottom of this thread.

Also, for a different filter (also executing while globally disabled...), an evaluation in one filter is done for item.PersonId == null, and another for item.PersonId != null and I get a NotImplementedException error "{"Unhandled Type of Object for Constant value null in LambdaToDbExpressionVisitor.VisitConstant"}. 

The first problem in general is the fact that globally disabled filters are executing.  

The second problem is that the Contains expression does not appear to be supported.  These dynamically generated filter expressions take the (TEntity item, (TProperty) value) => (evaluation here based against the filter scope variable "value").  TProperty is whatever the type of the property being compared in the expression based on the actual property that is used as an access rule criteria point.  In this case, the "value" is actually IEnumerable<TProperty> type where TProperty is assumed to be a type of Enum, so that a role or user can have a certain list of enumeration values that they are allowed to access on the TEntity (like in this case, Document entities can be 1 of 48 categories, and we want to restrict access for certain roles to only 2 of those categories.  These values are passed in as the "value" and then -> value.Contains(item.Category) is the actual evaluation in the dynamic expression.

The third problem as far as I can tell is that a constant "null" is not handled in expressions?

1st Exception (Contains expression)
=========================================================

```

   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.MapContainsExpression(MethodCallExpression expression)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, ObjectContext objectContext)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.BuildFilterExpressionWithDynamicFilters(String entityName, IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbScanExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbJoinExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbFilterExpression expression)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbFilterExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbSortExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbSortExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbLimitExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbLimitExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbJoinExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbJoinExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitBinary(DbBinaryExpression expression, Func`3 callback)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbUnionAllExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbUnionAllExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbSortExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbSortExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.<Created>b__0(IDbCommandTreeInterceptor i, DbCommandTreeInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateCommandDefinition(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CareConnext.WebControls.SearchViewModelBase`1.SetResults(IEnumerable`1 results) in c:\__Development__\Freelance\CareConnext\__PROJECTS__\Core\CareConnext\model\view\SearchViewModelBase.cs:line 67
   at CareConnext.Data.GenericRepository`1.Search(ISearchModel`1 model) in c:\__Development__\Freelance\CareConnext\__PROJECTS__\Core\CareConnext\data\repository\GenericRepository.cs:line 61
   at CareConnext.Data.AuditedRepository`1.SearchAuditable(ISearchModel`1 model) in c:\__Development__\Freelance\CareConnext\__PROJECTS__\Core\CareConnext\data\repository\AuditedRepository.cs:line 52
   at CareConnext.Business.SearchHandler.<>c__DisplayClass7`1.<SearchAuditableAsync>b__6() in c:\__Development__\Freelance\CareConnext\__PROJECTS__\Viewer\CareConnext.Business\handlers\SearchHandler.cs:line 33
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

2nd exception 
=========================================================================

```
  at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitConstant(ConstantExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, ObjectContext objectContext)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.BuildFilterExpressionWithDynamicFilters(String entityName, IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbScanExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitGroupExpressionBinding(DbGroupExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbGroupByExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpression(DbExpression expression)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBinding(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.VisitExpressionBindingEnterScope(DbExpressionBinding binding)
   at System.Data.Entity.Core.Common.CommandTrees.DefaultExpressionVisitor.Visit(DbProjectExpression expression)
   at EntityFramework.DynamicFilters.DynamicFilterInterceptor.TreeCreated(DbCommandTreeInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](TResult result, TInterceptionContext interceptionContext, Action`2 intercept)
   at System.Data.Entity.Infrastructure.Interception.DbCommandTreeDispatcher.Created(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
```

**Comment by jcachat** [comment]
The stack trace you are showing is not actually for a filter that is being executed and sent to the db server.  That stack trace shows the query compilation that happens the first time the query is executed.  And it will do all that stuff (including evaluating your filter) regardless of whether or not the filter is currently enabled.  That is necessary because EF only gives us 1 chance to evaluate the query and modify it (to inject our dynamic filter).  There is an extra condition that I add that is used to actually disable the filter (which just modifies the sql to ignore whatever other conditions are there).  The actual parameter values (and the "is filter disabled" flag) are injected into the raw SQL each time the query is sent to the db server.

For your second issue (the contains filter): Contains is supported (and there is a set of unit tests around it that you can see in the src).  But, the problem may be that you are using enums.  I will see if I can reproduce the problem that way and if there is something I can do about that.  And if that's why the exception is being thrown, then what I said above should explain why you are hitting it even when the filter is disabled.

I'll also need to go back and test your 3rd issue (with the null constant).  That should be supported and there are unit tests in NullTests.cs that should be covering it.  You should be able to work around it using "item.HasValue" or "!item.HasValue".

**Comment by themephs** [comment]
Good points, with the enums it is easy enough to convert them to integers assuming the DynamicFilters can support enum->int cast and then I can just pass in an enumerable of integers instead to represent the expression (only Enum properties generate these expressions and it will always use a simple Contains evaluation, so if the property can be cast to int then the variable passed in can be IEnumerable<int> instead since it is fixed for enum properties.

I'll try HasValue instead of the null checks as you have advised and let you know if there is still any issues.  I think the 3rd issue may just be a method stub that was never filled as somewhere in the stack trace it showed a NotImplementedException

**Comment by themephs** [comment]
So I tried changing the expressions around a bit.  Still getting errors on the Contains expression.  The stack trace is the exact same but has an additional line at the top of the stack:

The generated expression.ToString():

{(item, value) => value.Contains(Convert(item.DocumentType))}

(new line added in the exception)
 at System.Object.GetType()

(same as above)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.MapContainsExpression(MethodCallExpression expression)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at EntityFramework.DynamicFilters.LambdaToDbExpressionVisitor.Convert(DynamicFilterDefinition filter, DbExpressionBinding binding, ObjectContext objectContext)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.BuildFilterExpressionWithDynamicFilters(String entityName, IEnumerable`1 filterList, DbExpressionBinding binding, DbExpression predicate)
   at EntityFramework.DynamicFilters.DynamicFilterQueryVisitor.Visit(DbScanExpression expression)

**Comment by jcachat** [comment]
The Convert isn't supported.  We are limited in what we can do in that linq statement.  The conversion from enum->int will need to be handled internally.

For the null/HasValue issue: Can you post the relevant parts of the model and the filter that is failing?  I don't understand why that isn't working.

**Comment by themephs** [comment]
My mistake, it appears to be the same Contains expression after all, so I guess those are working.  Just need to solve the enum->int cast in the expression unless you think you can fix to support enum / IEnumerable<TEnum> types in the filter expressions.

**Comment by jcachat** [comment]
I'm going to check to see if I can support it inside the filter expressions.  It will be much cleaner that way.  I always prefer to make my properties Enum and let EF handle the conversion to int so I'd like the filtering to work the same way.

But I won't be able to work on it more until later tonight.  If I can't fix it tonight, I'll at least get you some kind of ETA or let you know if it's going to be a problem.  And I'll focus on the Contains issue since you at least have a workaround for the null issue.

**Comment by jcachat** [comment]
The Contains() problem was actually because you were using IEnumerable as the parameter type.  For some reason, IEnumerable.Contains() is stored into a linq expression differently than for List, IList, and IContains.  But I was able to make a small change to support it.  Pull down the latest and see if that fixes your problem.

I also took a look at the null issue.  And the error message you are getting is actually saying that the type "Object" (as in System.Object) is not valid.  Which is telling me that when you said you have a filter of "item.ParentId == null" that "ParentId" is of type System.Object.  That can't be translated into the EF/SQL query.  It must be an EF supported type.  Which is then confusing if the .HasValue workaround really did work because that should not have worked either if that's what is going on...

If that's not the case, I will need the relevant parts of your model and the full filter you are declaring so I can try to reproduce the problem.  At the moment, I cannot.

**Comment by themephs** [comment]
Well your latest update does work (so far, not getting the exception while
the filter is disabled...have not yet tested with the activated filter
though)!  Do you still want to take a look at the expression code?

**Comment by jcachat** [comment]
I'm still curious about why a filter on "item.PersonId == null" was throwing an exception (the 2nd exception in VisitConstant in your original post).  If you have a chance to re-test that and then send me the model & filter (assuming it still fails), I can take a look at what is happening there.

**Comment by themephs** [comment]
Well I can confirm the generated filters are all working as expected!  I'm really not sure why it was treating that expression as an object, because PersonId should be a Nullable<int> and the type is set by a generic.  Here is a snippet of the code where these expressions are generated.  The properties on any entity model with a certain attribute have a dynamic filter set aside for them based on the comparison enumerated type.  I.E. if you want to create a filterable condition based on PersonId, you can attribute the PersonId property twice, one with the Comparison type "IsNull" and one with "IsNotNull" to get two dynamic filters where an evaluation vs. HasValue or !HasValue is used.  

There are two expression invocation classes nested in the context for creating these during initialization:

```
`   protected override void OnFilterCreating(DbModelBuilder mb) {
            base.OnFilterCreating(mb);

            foreach (var type in TypeFactory.GetTypes<IModel>()) {
                foreach (var propertyInfo in type.GetProperties().Where(pi => pi.HasCustomAttribute<AccessFilterPropertyAttribute>())) {
                    foreach (var attr in propertyInfo.GetCustomAttributes<AccessFilterPropertyAttribute>()) {
                        if (propertyInfo.PropertyType.IsEnum) {
                            TypeWrapper.InvokeWrapper(typeof(_EnumFilterExpressionBuilder<,>),
                                                      new Type[] { type, propertyInfo.PropertyType }, 
                                                      mb, 
                                                      propertyInfo);
                        }
                        else {
                            TypeWrapper.InvokeWrapper(typeof(_PropertyFilterExpressionBuilder<,>),
                                                      new Type[] { type, propertyInfo.PropertyType },
                                                      mb,
                                                      propertyInfo,
                                                      attr.PropertyComparer);
                        }
                    }
                }
            }
        }
     
        private PartitionScopeContext GetPartitionScope() {
            return this.PartitionScope;
        }


        private class _EnumFilterExpressionBuilder<TModel, TProperty> : TypeWrapper where TModel : class, IModel {
            private readonly DbModelBuilder _builder;
            private readonly PropertyInfo _propertyInfo;

            public _EnumFilterExpressionBuilder(DbModelBuilder builder, PropertyInfo pi) {
                _builder = builder;
                _propertyInfo = pi;
            }

            public override void Run() {
                //System.Diagnostics.Debugger.Launch();
                var paramItem = Expression.Parameter(typeof(TModel), "item");
                var paramValues = Expression.Parameter(typeof(IEnumerable<TProperty>), "value");                
                
                var prop = Expression.Property(paramItem, _propertyInfo);
                //var cast = Expression.Convert(prop, typeof(Int32));

                MethodInfo mi = typeof(Enumerable).GetMethods()
                                                  .Where(m => m.Name.Equals("Contains"))
                                                  .Single(m => m.GetParameters().Length == 2)
                                                  .MakeGenericMethod(typeof(TProperty));

                var expContains = Expression.Call(null, mi, paramValues, prop);

                var lambda = Expression.Lambda<Func<TModel, IEnumerable<TProperty>, bool>>(expContains, paramItem, paramValues);

                string filterName = string.Format("AF__{0}_{1}_{2}", typeof(TModel).Name, _propertyInfo.Name, "Enum");

                _builder.Filter(filterName, lambda, new List<TProperty>());
                _builder.DisableFilterGlobally(filterName);
            }
        }

        private class _PropertyFilterExpressionBuilder<TModel, TProperty> : TypeWrapper where TModel : class, IModel {
            private readonly DbModelBuilder _builder;
            private readonly PropertyInfo _propertyInfo;
            private readonly Comparison _comparison;

            public _PropertyFilterExpressionBuilder(DbModelBuilder builder, PropertyInfo pi, Comparison comparison) {
                _builder = builder;
                _propertyInfo = pi;
                _comparison = comparison;
            }

            public override void Run() {
                var paramItem = Expression.Parameter(typeof(TModel), "item");
                var paramValue = Expression.Parameter(typeof(TProperty), "value");

                var prop = Expression.Property(paramItem, _propertyInfo);
                
                var expComparison = (_propertyInfo.PropertyType.IsGenericType &&
                                     _propertyInfo.PropertyType.GetGenericTypeDefinition().IsEquivalentTo(typeof(Nullable<>).GetGenericTypeDefinition()) &&
                                     _comparison.IsAnyOf(Comparison.IsNull, Comparison.IsNotNull))
                                        ? GetNullableComparisonExpression(prop, _comparison)
                                        : Comparer.GetComparisonExpression(prop, _comparison, paramValue);

                var lambda = Expression.Lambda<Func<TModel, TProperty, bool>>(expComparison, paramItem, paramValue);

                string filterName = string.Format("AF__{0}_{1}_{2}", typeof(TModel).Name, _propertyInfo.Name, _comparison.ToString());

                _builder.Filter(filterName, lambda, default(TProperty));
                _builder.DisableFilterGlobally(filterName);
            }

            private Expression GetNullableComparisonExpression(MemberExpression exp, Comparison comparison) {
                return (comparison == Comparison.IsNotNull) ? Expression.Property(exp, "HasValue") as Expression
                                                            : Expression.Not(Expression.Property(exp, "HasValue")) as Expression;
            }
        }
```

**Comment by themephs** [comment]
The filters are by default globally disabled and during a request a cached list of user/role associations to those filters are enabled only in that scope (not globally) for that user/role based request, and their allowed values for those expressions are injected into the "value" argument of the expression using SetFilterScopeParameter.  

Assume though originally for 

 ```
     var expComparison = (_propertyInfo.PropertyType.IsGenericType &&
                                     _propertyInfo.PropertyType.GetGenericTypeDefinition().IsEquivalentTo(typeof(Nullable<>).GetGenericTypeDefinition()) &&
                                     _comparison.IsAnyOf(Comparison.IsNull, Comparison.IsNotNull))
                                        ? GetNullableComparisonExpression(prop, _comparison)
                                        : Comparer.GetComparisonExpression(prop, _comparison, paramValue);

```

The IsNull/IsNotNull comparison was doing the original expression I told you of, where it was item.PersonId != null or item.PersonId == null.

This is the expression that would be used for a non Nullable<T> type still.  But maybe you can see why this tripped that exception, where it should have correctly cast the filter to <TModel, TProperty, bool> where TProperty should've been typeof(int?) based on the pattern above.

**Comment by jcachat** [comment]
It's going to be pretty difficult for me to determine from looking at your code.  That's a pretty complicated setup.  I would need to be able to use a debugger to step through it to examine how the expressions are being created.

If there's a full project example you can send me, I'd be happy to take a closer look at it.  But otherwise, if the "HasValue" method is working for you, maybe we just leave it at that.

**Comment by themephs** [comment]
I'd have to link you up to the whole solution which is proprietary code unfortunately.  But yeah it's working perfectly.
