### ISSUE TITLE
AlterTableAnnotations code first migration fails on **postgres**

### ISSUE THREAD

**Issue by tiwariarvin** [jcachat/EntityFramework.DynamicFilters#60]
Is there a work around?

I am getting error = "Unhandled MigrationOperation AlterTableOperation in NpgsqlMigrationSqlGenerator"

Stack trace on PM -
Applying explicit migration: 201604041142031_test.
System.NotImplementedException: Unhandled MigrationOperation AlterTableOperation in NpgsqlMigrationSqlGenerator
   at Npgsql.NpgsqlMigrationSqlGenerator.Convert(IEnumerable`1 operations)
   at Npgsql.NpgsqlMigrationSqlGenerator.Generate(IEnumerable`1 migrationOperations, String providerManifestToken)
   at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)

**Comment by tiwariarvin** [comment]
FYI.. I am using PostgresSQL 9.4. Thank you for any help in advance, this library is really helpful. 

~Arvin

**Comment by jcachat** [comment]
The error you're getting seems to imply that it may be a problem with the Postgres driver not supporting an "alter table" statement in your migration.  Which should be unrelated to DynamicFilters since we don't alter the structure of any tables.

If it's definitely a filter that is causing the issue (i.e. it doesn't happen if you disable the filter), I would need to see the filter and the related model.  And since there is a migration involved, I may need you to create a test project that will reproduce the problem as I'm not sure I would be able to duplicate the exact migration that is taking place.

**Comment by tiwariarvin** [comment]
Thanks JcaChat. I agree, Postgres driver lacks support for "AlterTableAnnotation". I am taking this up on "Postgre" GIT. 

But just curious, Is there a way to disable "annotation" only? I know this is for performance, but can we disable this alone?

For any reference, below migration caused this exception-
AlterTableAnnotations(
                "schema.table",
                c => new
                    {
                        //some code 
                    },
                annotations: new Dictionary<string, AnnotationValues>
                {
                    { 
                        "DynamicFilter_Annoucement_IsDeleted",
                        new AnnotationValues(oldValue: null, newValue: "EntityFramework.DynamicFilters.DynamicFilterDefinition")
                    },
                });

**Comment by jcachat** [comment]
The library stores information about the filter by adding a "Convention" to it.  That Convention adds a Table Annotation which contains information about the filter.  None of this should be written to the database!  The Conventions are applied by the Filter() commands in OnModelCreating().  I have not seen any other database driver attempt to do that.

The Conventions/Table Attributes are not for performance reasons.  This is how we attach information about the filter to the underlying EF entities so that we can get the filter definitions when the query is being executed.  It is not possible to do this any other way that I know of.

I had not specifically tested against Postgres, but another user did (see #44) and it was working...  He was on 9.3 and you are on 9.4.  Maybe it's a driver change.  Is it possible for you to try rolling back to 9.3 to see if that works to at least determine if it's a driver change?

**Comment by gpezzino** [comment]
Hi,
I am having the same kind of error. My application uses EntityFramework 6.1.3 and DynamicFilters 1.4.10.2.

In my OnModelCreating I added the following:

`modelBuilder.Filter( "Multitenancy", ( IMultitenancyEntity entity, IEnumerable<string> availableCodes ) => availableCodes == null || availableCodes.Contains( entity.SubscriberCode ), GetSubscriberCodesForCurrentUser );`

and when I started the application I got the message that the model backing the database was not updated.
So I run Add-Migration, and this is the code generated:
`public override void Up() {
	AlterTableAnnotations(
		"dbo.Companies",
		c => new {
			Id = c.Int(nullable: false, identity: true),
			Name = c.String(nullable: false, maxLength: 50),
			Type = c.Int(nullable: false),
			Code = c.String(maxLength: 10),
		},
		annotations: new Dictionary<string, AnnotationValues>{
			{ 
				"DynamicFilter_Company_Multitenancy",
				new AnnotationValues(oldValue: null, newValue: "EntityFramework.DynamicFilters.DynamicFilterDefinition")
			},
		});
}`

I then run Update-Database, and the Seed method throws the following exception:
System.NotImplementedException: Unhandled Type of Object for Constant value null in LambdaToDbExpressionVisitor.VisitConstant.

Any ideas about how to solve this problem?

**Comment by tiwariarvin** [comment]
@gpezzino - you may override SQL generator to ignore AlterTableAnnotation as one of colleague did this in our projects -

public class MyNPGSqlGenerator : NpgsqlMigrationSqlGenerator 
    {
        public override IEnumerable<System.Data.Entity.Migrations.Sql.MigrationStatement> Generate(IEnumerable<System.Data.Entity.Migrations.Model.MigrationOperation> operations, string providerManifestToken)
        {
            var statments = new List<MigrationOperation>();
            foreach (var item in operations)
            {
                var migration = item as AlterTableOperation;
                if (migration == null)
                {
                    statments.Add(item);
                }
            }
            return base.Generate(statments, providerManifestToken);
        }
    } 

@jcachat: I am marking this closed

**Comment by tiwariarvin** [comment]
Just to add, I have logged an issue for "AlterTableAnnotation" support in npgsql GIT 

[https://github.com/npgsql/EntityFramework6.Npgsql/issues/33](url)

There it needs an empty implementation to avoid such errors.

**Comment by Laoujin** [comment]
I'm just reposting tiwariarvin's solution with formatting.
This solved the problem for me perfectly.

```
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations.Model;
using System.Data.Entity.Migrations.Sql;
using Npgsql;

public class MyNpgsqlGenerator : NpgsqlMigrationSqlGenerator
{
    public override IEnumerable<MigrationStatement> Generate(IEnumerable<MigrationOperation> operations, string providerManifestToken)
    {
        var statements = new List<MigrationOperation>();
        foreach (var item in operations)
        {
            var migration = item as AlterTableOperation;
            if (migration == null)
            {
                statements.Add(item);
            }
        }
        return base.Generate(statements, providerManifestToken);
    }
}

public class MyDbConfiguration : DbConfiguration
{
    public MyDbConfiguration()
    {
        SetDefaultConnectionFactory(new NpgsqlConnectionFactory());
        SetMigrationSqlGenerator("Npgsql", () => new MyNpgsqlGenerator());
        SetProviderFactory("Npgsql", NpgsqlFactory.Instance);
        SetProviderServices("Npgsql", NpgsqlServices.Instance);
    }
}
```

**Comment by Worthy7** [comment]
@tiwariarvin its gone?
